version: "3.8"
services:
  postgres:
    image: postgres:15
    container_name: bizzinsight_b
    restart: always
    environment:
      POSTGRES_DB: bizinsight360
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Applying
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - default

volumes:
  postgres_data:
